export { registerGlobalAssistantRoutes } from "./globalAssistant/routes";
export { getOpenAIClient, getErrorMessage } from "./globalAssistant/openai";
export { SYSTEM_PROMPT } from "./globalAssistant/prompts";
export { searchWeb, shouldSearchWeb, searchEntities } from "./globalAssistant/search";
export type { WebSearchTriggerResult, SearchResult } from "./globalAssistant/search";
export { getSmartInsights, getDynamicSuggestions, getPageSuggestions } from "./globalAssistant/insights";
export type { SmartInsight } from "./globalAssistant/insights";
export { getBoundedBusinessContext, getBusinessStats } from "./globalAssistant/context";
export type { ContextIntent } from "./globalAssistant/context";
export { buildBudgetedContext, limitWebResults, truncateToFit, DEFAULT_BUDGET } from "./globalAssistant/tokenBudget";
export type { TokenBudget } from "./globalAssistant/tokenBudget";
export { cacheGet, cacheSet, getCacheKey, cacheDelPrefix, cleanExpiredCache, CACHE_TTL } from "./globalAssistant/cache";
export { AI_CONFIG, getModelWithFallback, enableFallbackModel, resetToDefaultModel, isModelNotFoundError } from "./globalAssistant/config";
export { withRetry, isRetryableError } from "./globalAssistant/retry";
export type { RetryOptions } from "./globalAssistant/retry";
