import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { Shield, Key, Lock, Unlock, AlertTriangle, CheckCircle2, RefreshCw, Copy } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface UserSecurityProps {
  userId: string;
  username: string;
  name: string;
  twoFactorEnabled?: boolean;
  lastLoginAt?: Date | null;
  failedLoginAttempts?: number;
  accountLockedUntil?: Date | null;
  onUpdate?: () => void;
}

export function UserSecurityManagement({
  userId,
  username,
  name,
  twoFactorEnabled = false,
  lastLoginAt,
  failedLoginAttempts = 0,
  accountLockedUntil,
  onUpdate,
}: UserSecurityProps) {
  const { toast } = useToast();
  const [showResetPassword, setShowResetPassword] = useState(false);
  const [showBackupCodes, setShowBackupCodes] = useState(false);
  const [loading, setLoading] = useState(false);
  const [tempPassword, setTempPassword] = useState("");
  const [backupCodes, setBackupCodes] = useState<string[]>([]);

  const isAccountLocked = accountLockedUntil ? new Date(accountLockedUntil) > new Date() : false;

  const handleResetPassword = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/auth/admin/reset-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId }),
        credentials: "include",
      });

      const data = await response.json();

      if (!response.ok) {
        toast({
          title: "Error",
          description: data.error || "Failed to reset password",
          variant: "destructive",
        });
        return;
      }

      setTempPassword(data.temporaryPassword);
      toast({
        title: "Password Reset",
        description: `Temporary password generated for ${name}",
      });
      onUpdate?.();
    } catch (error) {
      toast({
        title: "Error",
        description: "An unexpected error occurred",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleUnlockAccount = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/users/" + userId, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          failedLoginAttempts: 0,
          accountLockedUntil: null,
        }),
        credentials: "include",
      });

      if (!response.ok) {
        throw new Error("Failed to unlock account");
      }

      toast({
        title: "Account Unlocked",
        description: `${name}'s account has been unlocked`,
      });
      onUpdate?.();
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to unlock account",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleRegenerateBackupCodes = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/auth/regenerate-backup-codes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetUserId: userId }),
        credentials: "include",
      });

      const data = await response.json();

      if (!response.ok) {
        toast({
          title: "Error",
          description: data.error || "Failed to regenerate backup codes",
          variant: "destructive",
        });
        return;
      }

      setBackupCodes(data.backupCodes);
      setShowBackupCodes(true);
      toast({
        title: "Backup Codes Regenerated",
        description: `New backup codes generated for ${name}`,
      });
      onUpdate?.();
    } catch (error) {
      toast({
        title: "Error",
        description: "An unexpected error occurred",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied",
      description: "Copied to clipboard",
    });
  };

  const downloadBackupCodes = () => {
    const text = `TrueNorthOS Backup Codes\n\nUsername: ${username}\nName: ${name}\nGenerated by Admin: ${new Date().toLocaleDateString()}\n\n${backupCodes.map((code, i) => `${i + 1}. ${code}`).join('\n')}\n\n⚠️ IMPORTANT:\n- Each code can only be used once\n- Give these codes to the user securely\n- User should store them in a safe location`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `backup-codes-${username}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Shield className="w-5 h-5" />
          Security Management
        </CardTitle>
        <CardDescription>
          Manage authentication and account security for {name}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Security Status */}
        <div className="grid grid-cols-2 gap-3">
          <div className="flex items-center gap-2">
            <Shield className={`w-4 h-4 ${twoFactorEnabled ? 'text-green-600' : 'text-amber-600'}`} />
            <span className="text-sm">2FA Status:</span>
            <Badge variant={twoFactorEnabled ? "default" : "secondary"}>
              {twoFactorEnabled ? "Enabled" : "Not Set Up"}
            </Badge>
          </div>

          <div className="flex items-center gap-2">
            <Lock className="w-4 h-4" />
            <span className="text-sm">Failed Attempts:</span>
            <Badge variant={failedLoginAttempts >= 3 ? "destructive" : "secondary"}>
              {failedLoginAttempts}
            </Badge>
          </div>
        </div>

        {lastLoginAt && (
          <div className="text-sm text-muted-foreground">
            Last login: {new Date(lastLoginAt).toLocaleString()}
          </div>
        )}

        {/* Account Locked Warning */}
        {isAccountLocked && (
          <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertDescription>
              Account is locked until {new Date(accountLockedUntil!).toLocaleTimeString()}
            </AlertDescription>
          </Alert>
        )}

        {/* Action Buttons */}
        <div className="grid grid-cols-2 gap-3">
          <Button
            onClick={() => setShowResetPassword(true)}
            variant="outline"
            className="w-full"
            disabled={loading}
          >
            <Key className="w-4 h-4 mr-2" />
            Reset Password
          </Button>

          {isAccountLocked && (
            <Button
              onClick={handleUnlockAccount}
              variant="outline"
              className="w-full"
              disabled={loading}
            >
              <Unlock className="w-4 h-4 mr-2" />
              Unlock Account
            </Button>
          )}

          {twoFactorEnabled && (
            <Button
              onClick={handleRegenerateBackupCodes}
              variant="outline"
              className="w-full"
              disabled={loading}
            >
              <RefreshCw className="w-4 h-4 mr-2" />
              Regenerate Backup Codes
            </Button>
          )}
        </div>

        {/* Reset Password Dialog */}
        <Dialog open={showResetPassword} onOpenChange={setShowResetPassword}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Reset Password for {name}</DialogTitle>
              <DialogDescription>
                This will generate a new temporary password. The user will be forced to change it on their next login.
              </DialogDescription>
            </DialogHeader>

            {tempPassword ? (
              <div className="space-y-4">
                <Alert>
                  <CheckCircle2 className="h-4 w-4" />
                  <AlertDescription>
                    Temporary password generated successfully!
                  </AlertDescription>
                </Alert>

                <div className="space-y-2">
                  <Label>Temporary Password</Label>
                  <div className="flex gap-2">
                    <Input
                      value={tempPassword}
                      readOnly
                      className="font-mono"
                    />
                    <Button
                      size="icon"
                      variant="outline"
                      onClick={() => copyToClipboard(tempPassword)}
                    >
                      <Copy className="w-4 h-4" />
                    </Button>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    ⚠️ Copy this password and give it to {name} securely. This is the only time it will be shown.
                  </p>
                </div>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">
                Click "Generate Password" to create a new temporary password for this user.
              </p>
            )}

            <DialogFooter>
              {tempPassword ? (
                <Button onClick={() => {
                  setTempPassword("");
                  setShowResetPassword(false);
                }}>
                  Done
                </Button>
              ) : (
                <>
                  <Button
                    variant="outline"
                    onClick={() => setShowResetPassword(false)}
                  >
                    Cancel
                  </Button>
                  <Button onClick={handleResetPassword} disabled={loading}>
                    {loading ? "Generating..." : "Generate Password"}
                  </Button>
                </>
              )}
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Backup Codes Dialog */}
        <Dialog open={showBackupCodes} onOpenChange={setShowBackupCodes}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>New Backup Codes for {name}</DialogTitle>
              <DialogDescription>
                These codes replace all previous backup codes. Give them to the user securely.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4">
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-4">
                <div className="grid grid-cols-2 gap-2">
                  {backupCodes.map((code, i) => (
                    <div key={i} className="font-mono text-sm bg-white p-2 rounded border text-center">
                      {i + 1}. {code}
                    </div>
                  ))}
                </div>
              </div>

              <Alert>
                <AlertTriangle className="h-4 w-4" />
                <AlertDescription>
                  Each code can only be used once. Download or copy these codes before closing.
                </AlertDescription>
              </Alert>
            </div>

            <DialogFooter className="flex-col sm:flex-row gap-2">
              <Button
                variant="outline"
                onClick={downloadBackupCodes}
                className="w-full sm:w-auto"
              >
                Download Codes
              </Button>
              <Button
                variant="outline"
                onClick={() => copyToClipboard(backupCodes.join('\n'))}
                className="w-full sm:w-auto"
              >
                Copy All
              </Button>
              <Button
                onClick={() => {
                  setBackupCodes([]);
                  setShowBackupCodes(false);
                }}
                className="w-full sm:w-auto"
              >
                Done
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
}
